### ISSUE TITLE
聊天室记录

### ISSUE THREAD

**Issue by marren06** [easemob/livestream_demo_android#5]
demo中的聊天室历史记录  进入后会默认显示10条  这10条数据怎么找不到在哪获取的啊？ 也没有调用fromDb那个方法获取聊天室记录啊

**Comment by lzan13** [comment]
这个10条记录是服务器自动下发的，不需要你获取，不过现在环信默认应该是关闭了10条消息的推送，你可以联系上午或者客服咨询下
